### ISSUE TITLE
Upgrade to JTS ≥1.17.0

### ISSUE THREAD

**Issue by stokwisz** [jawg/geojson-jackson-jts-extensions#2]
With [release of JTS 1.17.0](https://github.com/locationtech/jts/releases/tag/1.17.0) binary incompatible change was introduced to some method of `Polygon`:

> Change `Polygon` `getExteriorRing` and `getInteriorRingN` accessors to return `LinearRing`.
> This is a binary incompatible change to the method signature. Recompilation is necessary. No source code changes are required.

This issue should be addressed by PR's upgrading dependency to JTS to have it at least in v1.17.0.

**Comment by stokwisz** [comment]
Hi @clementgayvallet, would it be possible to look this issue regarding updating JTS dependency? Is there something that I can do on my own to speed up a bit of the review process? Thanks in advance for your input here. ;-)

**Comment by clementgayvallet** [comment]
Hi @stokwisz, I upgraded JTS to its latest version. Let me know if it fixes your issue. :)

**Comment by stokwisz** [comment]
Sorry for delayed answer – everything looks good. Thank you for your effort. 

Please decide on your own what to do with open PRs:
- #3 
- #4
